#!/bin/bash
# Builds LiteCurrency API as Docker image, and runs it locally on port 8000.

if !command -v docker &> /dev/null
then
    echo "docker is not installed, or not available in commandline"
    exit 1
fi

docker build -t litecurrency .
docker run -p 8000:8000 litecurrency
