name: MyPy Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  

    - name: Install dependencies
      run: pip install mypy

    - name: Run MyPy
      run: mypy . --install-types

    - name: Check for MyPy errors
      run: |
        if [ $? -eq 0 ]; then
          echo "MyPy check passed."
        else
          echo "MyPy check failed. Please fix the errors and try again."
          exit 1
        fi

